version: 2
jobs:
  build:
    working_directory: ~/django-pgviews
    docker:
      - image: circleci/python:3.7
    parallelism: 1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
#      - restore_cache:
#          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install -r tests/requirements.txt --user
      - run:
          command: |
            python setup.py build
            python setup.py install
#            TODO: Redo django in tests and fix django.setup error and wsgi specific errors.
#            python setup.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1